import type { DateValue } from "@/lib/dates/date-value";
import type { Person, Relationship } from "./types";

/**
 * Wholly fictional demo family, kept only for local development/testing
 * reference (CLAUDE.md 24: seed must never contain real family data).
 * Not used by any page since Stage 2 — those read real data from
 * Supabase via server/repositories/people.ts. Includes a former-spouse-
 * with-child case, two placeholder parents, and a first-cousin marriage
 * so the tree/layout code was exercised against non-trivial topology
 * before real data existed.
 */

export type FixturePerson = Person;
export type FixtureRelationship = Relationship;

function year(y: number): DateValue {
  return { precision: "year", start: `${y}-01-01`, end: `${y}-01-01`, text: null };
}

const unknownDate: DateValue = { precision: "unknown", start: null, end: null, text: null };

export const fixturePeople: FixturePerson[] = [
  {
    id: "p-ivan",
    firstName: "Иван",
    middleName: "Петрович",
    lastName: "Огурцов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: true,
    birth: year(1925),
    death: year(1990),
    birthPlace: "г. Тверь",
    deathPlace: "г. Москва",
    profession: "Инженер",
    education: "Московский энергетический институт",
    shortBio: "Работал на заводе всю жизнь, увлекался рыбалкой.",
    photoUrl: null,
  },
  {
    id: "p-maria",
    firstName: "Мария",
    middleName: "Сергеевна",
    lastName: "Огурцова",
    maidenName: "Смирнова",
    isPlaceholder: false,
    isDeceased: true,
    birth: year(1928),
    death: year(2005),
    birthPlace: "г. Тверь",
    deathPlace: "г. Москва",
    profession: "Учитель начальных классов",
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-petr",
    firstName: "Пётр",
    middleName: "Иванович",
    lastName: "Огурцов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1950),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: "Врач",
    education: "1-й Московский медицинский институт",
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-natalia",
    firstName: "Наталья",
    middleName: "Игоревна",
    lastName: "Огурцова",
    maidenName: "Белова",
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1951),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-elena",
    firstName: "Елена",
    middleName: "Павловна",
    lastName: "Огурцова",
    maidenName: "Волкова",
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1952),
    death: null,
    birthPlace: "г. Ленинград",
    deathPlace: null,
    profession: "Бухгалтер",
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-olga",
    firstName: "Ольга",
    middleName: "Ивановна",
    lastName: "Кузнецова",
    maidenName: "Огурцова",
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1955),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: "Экономист",
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-viktor",
    firstName: "Виктор",
    middleName: "Николаевич",
    lastName: "Кузнецов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1953),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-nikolai",
    firstName: "Николай",
    middleName: "Иванович",
    lastName: "Огурцов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1958),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-unknown-mother-oksana",
    firstName: "Неизвестная мать",
    middleName: null,
    lastName: null,
    maidenName: null,
    isPlaceholder: true,
    isDeceased: false,
    birth: unknownDate,
    death: unknownDate,
    birthPlace: null,
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-sergei",
    firstName: "Сергей",
    middleName: "Петрович",
    lastName: "Огурцов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1976),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-dmitry",
    firstName: "Дмитрий",
    middleName: "Петрович",
    lastName: "Огурцов",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1980),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: "Программист",
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-anna",
    firstName: "Анна",
    middleName: "Викторовна",
    lastName: "Огурцова",
    maidenName: "Кузнецова",
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1978),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: "Дизайнер",
    education: null,
    shortBio: null,
    photoUrl: null,
  },
  {
    id: "p-oksana",
    firstName: "Оксана",
    middleName: "Николаевна",
    lastName: "Огурцова",
    maidenName: null,
    isPlaceholder: false,
    isDeceased: false,
    birth: year(1985),
    death: null,
    birthPlace: "г. Москва",
    deathPlace: null,
    profession: null,
    education: null,
    shortBio: null,
    photoUrl: null,
  },
];

export const fixtureRelationships: FixtureRelationship[] = [
  { id: "r-1", fromPersonId: "p-ivan", toPersonId: "p-maria", relationshipType: "spouse", parentRole: null },
  { id: "r-2", fromPersonId: "p-ivan", toPersonId: "p-petr", relationshipType: "biological_parent", parentRole: "father" },
  { id: "r-3", fromPersonId: "p-maria", toPersonId: "p-petr", relationshipType: "biological_parent", parentRole: "mother" },
  { id: "r-4", fromPersonId: "p-ivan", toPersonId: "p-olga", relationshipType: "biological_parent", parentRole: "father" },
  { id: "r-5", fromPersonId: "p-maria", toPersonId: "p-olga", relationshipType: "biological_parent", parentRole: "mother" },
  { id: "r-6", fromPersonId: "p-ivan", toPersonId: "p-nikolai", relationshipType: "biological_parent", parentRole: "father" },
  { id: "r-7", fromPersonId: "p-maria", toPersonId: "p-nikolai", relationshipType: "biological_parent", parentRole: "mother" },

  { id: "r-8", fromPersonId: "p-petr", toPersonId: "p-natalia", relationshipType: "former_spouse", parentRole: null },
  { id: "r-9", fromPersonId: "p-petr", toPersonId: "p-sergei", relationshipType: "biological_parent", parentRole: "father" },
  { id: "r-10", fromPersonId: "p-natalia", toPersonId: "p-sergei", relationshipType: "biological_parent", parentRole: "mother" },

  { id: "r-11", fromPersonId: "p-petr", toPersonId: "p-elena", relationshipType: "spouse", parentRole: null },
  { id: "r-12", fromPersonId: "p-petr", toPersonId: "p-dmitry", relationshipType: "biological_parent", parentRole: "father" },
  { id: "r-13", fromPersonId: "p-elena", toPersonId: "p-dmitry", relationshipType: "biological_parent", parentRole: "mother" },

  { id: "r-14", fromPersonId: "p-olga", toPersonId: "p-viktor", relationshipType: "spouse", parentRole: null },
  { id: "r-15", fromPersonId: "p-olga", toPersonId: "p-anna", relationshipType: "biological_parent", parentRole: "mother" },
  { id: "r-16", fromPersonId: "p-viktor", toPersonId: "p-anna", relationshipType: "biological_parent", parentRole: "father" },

  { id: "r-17", fromPersonId: "p-nikolai", toPersonId: "p-oksana", relationshipType: "biological_parent", parentRole: "father" },
  {
    id: "r-18",
    fromPersonId: "p-unknown-mother-oksana",
    toPersonId: "p-oksana",
    relationshipType: "biological_parent",
    parentRole: "mother",
  },

  { id: "r-19", fromPersonId: "p-dmitry", toPersonId: "p-anna", relationshipType: "spouse", parentRole: null },
];
